repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-merge-conflict
      - id: flake8
        additional_dependencies:
          - flake8-commas
          - flake8-docstrings
          - flake8-import-order
          - flake8-quotes
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
